#!/bin/bash

OEM_USER=slimbook-oem

function run_installer
{
    export XDG_DATA_DIRS=/usr/share/calamares-settings-slimbook/:$XDG_DATA_DIRS:/usr/share
    export XDG_CONFIG_DIRS=/usr/share/calamares-settings-slimbook/installer:$XDG_CONFIG_DIRS:/etc/xdg

    if [ -f /var/lib/slimbook.installer.oem ]; then
        export XDG_CONFIG_DIRS=/usr/share/calamares-settings-slimbook/oem:$XDG_CONFIG_DIRS:/etc/xdg
    fi

    export QT_STYLE_OVERRIDE=adwaita
    calamares -X

}

function enable_oem
{
    touch /var/lib/slimbook.installer.oem

    id -u $OEM_USER

    if [ $? -eq 1 ]; then
        adduser --firstuid 900 --shell /bin/bash --gecos "Slimbook OEM" $OEM_USER
    fi

    passwd -d $OEM_USER
    usermod -U $OEM_USER
    usermod -a -G sudo $OEM_USER

    # enable gdm autologin
    if [ -f /usr/sbin/gdm3 ]; then
        cp /etc/gdm3/custom.conf /etc/gdm3/custom.conf.orig || true
        echo -e "[daemon]\nAutomaticLoginEnable=True\nAutomaticLogin=${OEM_USER}\n" > /etc/gdm3/custom.conf
    fi

    # enable sddm autologin
    if [ -f /usr/bin/sddm ]; then
        cp /etc/sddm.conf /etc/sddm.conf.orig || true
        echo -e "[Autologin]\nSession=plasma.desktop\nUser=${OEM_USER}\n" > /etc/sddm.conf
    fi

    if [ -f /var/lib/slimbook.installer.done ]; then
        rm /var/lib/slimbook.installer.done
    fi

    cp /usr/share/calamares-settings-slimbook/slimbook-installer-autostart.desktop /etc/xdg/autostart/
    cp /usr/share/calamares-settings-slimbook/slimbook-installer.desktop /usr/share/applications/
}

function disable_oem
{
    if [ -f /var/lib/slimbook.installer.oem ]; then
        rm /var/lib/slimbook.installer.oem

        # restore gdm settings
        if [ -f /usr/sbin/gdm3 ]; then
            mv /etc/gdm3/custom.conf.orig /etc/gdm3/custom.conf || true
        fi

        # restore sddm settings
        if [ -f /usr/bin/sddm ]; then
            rm /etc/sddm.conf || true

            if [ -f /etc/sddm.conf.orig ]; then
                mv /etc/sddm.conf.orig /etc/sddm.conf
            fi
        fi

        if [ -f /var/lib/AccountsService/users/$OEM_USER ]; then
            rm -rf /var/lib/AccountsService/users/$OEM_USER
        fi

        id -u $OEM_USER
        if [ $? -eq 0 ]; then
            usermod -L $OEM_USER
        fi

        rm /etc/xdg/autostart/slimbook-installer-autostart.desktop
        rm /usr/share/applications/slimbook-installer.desktop
        touch /var/lib/slimbook.installer.done
    fi

}

function autostart
{
    run_installer
}

function install_extra_packages
{
    model_str=`slimbookctl info | grep model | cut -d ":" -f 2`
    family=`echo $model_str | sed -e 's/0x\(.*\)../\1/'`

    case $family in

        "1")
            echo "* Slimbook Executive"
            meta="slimbook-meta-executive"
            packages="slimbookintelcontroller"
        ;;

        "2")
            echo "* Slimbook ProX"
            meta="slimbook-meta-prox"
            packages="slimbookamdcontroller"
        ;;

        "4")
            echo "* Slimbook Titan"
            meta="slimbook-meta-titan"
        ;;

        "8")
            echo "* Slimbook Hero"
            meta="slimbook-meta-hero"
        ;;

        "10")
            echo "* Slimbook Essential"
            meta="slimbook-meta-elemental"
            packages="slimbookintelcontroller"
        ;;

        "20")
            echo "* Slimbook Elemental"
            meta="slimbook-meta-elemental"
            packages="slimbookintelcontroller"
        ;;

        "40")
            echo "* Slimbook Excalibur"
            meta="slimbook-meta-excalibur"
        ;;

        "80")
            echo "* Slimbook Hero-S"
            meta="slimbook-meta-hero-s"
            packages="slimbookintelcontroller"
        ;;

        *)
            echo "* Unknown model:"
            echo `slimbookctl info | grep model`
        ;;

    esac

if [ ! -z "$meta" ]; then
    echo "* Installing meta: ${meta}"
    /usr/bin/apt -y install $meta || true
fi

if [ ! -z "$packages" ]; then
    echo -e "\n* Installing extra packages: ${packages}"
    /usr/bin/apt -y install $packages || true
fi

}

case $1 in
    "--enable-oem")
        enable_oem
    ;;

    "--disable-oem")
        disable_oem
    ;;

    "--autostart")
        autostart
    ;;

    "--install-extra-packages")
        install_extra_packages
    ;;

    *)
        run_installer
    ;;
esac
