#!/bin/bash

OEM_USER=slimbook-oem

function run_installer
{
    export XDG_DATA_DIRS=/usr/share/calamares-settings-slimbook/:$XDG_DATA_DIRS:/usr/share
    export XDG_CONFIG_DIRS=/usr/share/calamares-settings-slimbook/installer:$XDG_CONFIG_DIRS:/etc/xdg

    if [ -f /var/lib/slimbook.installer.oem ]; then
        export XDG_CONFIG_DIRS=/usr/share/calamares-settings-slimbook/oem:$XDG_CONFIG_DIRS:/etc/xdg
    fi

    export QT_STYLE_OVERRIDE=adwaita
    calamares -X

}

function enable_oem
{
    touch /var/lib/slimbook.installer.oem
    cp /etc/gdm3/custom.conf /etc/gdm3/custom.conf.orig

    id -u $OEM_USER

    if [ $? -eq 1 ]; then
        adduser --firstuid 2000 --shell /bin/bash --gecos "Slimbook OEM" $OEM_USER
    fi

    passwd -d $OEM_USER
    usermod -U $OEM_USER
    usermod -a -G sudo $OEM_USER

    echo -e "[daemon]\nAutomaticLoginEnable=True\nAutomaticLogin=${OEM_USER}\n" > /etc/gdm3/custom.conf

    if [ -f /var/lib/slimbook.installer.done ]; then
        rm /var/lib/slimbook.installer.done
    fi

    cp /usr/share/calamares-settings-slimbook/slimbook-installer-autostart.desktop /etc/xdg/autostart/
    cp /usr/share/calamares-settings-slimbook/slimbook-installer.desktop /usr/share/applications/
}

function disable_oem
{
    if [ -f /var/lib/slimbook.installer.oem ]; then
        rm /var/lib/slimbook.installer.oem
        cp /etc/gdm3/custom.conf.orig /etc/gdm3/custom.conf

        id -u $OEM_USER
        if [ $? -eq 0 ]; then
            usermod -L $OEM_USER
        fi

        rm /etc/xdg/autostart/slimbook-installer-autostart.desktop
        rm /usr/share/applications/slimbook-installer.desktop
        touch /var/lib/slimbook.installer.done
    fi

}

function autostart
{
    run_installer
}

function install_extra_packages
{
    model_str=`slimbookctl info | grep model | cut -d ":" -f 2`
    family=`echo $model_str | sed -e 's/0x\(.*\)../\1/'`

    echo ${family} > /tmp/slimbook.txt
}

case $1 in
    "--enable-oem")
        enable_oem
    ;;

    "--disable-oem")
        disable_oem
    ;;

    "--autostart")
        autostart
    ;;

    "--install-extra-packages")
        install_extra_packages
    ;;

    *)
        run_installer
    ;;
esac
