#!/bin/sh

set -e

PACKAGE_NAME="calamares-settings-slimbook"
ORIGINAL_FILE="/usr/share/applications/calamares.desktop"
DIVERT_FILE="/usr/share/applications/calamares.desktop.divert"

case "$1" in
    configure)
        if [ ! -f /var/lib/slimbook.installer.done ]; then
            cp /usr/share/calamares-settings-slimbook/slimbook-installer-autostart.desktop /etc/xdg/autostart/
            cp /usr/share/calamares-settings-slimbook/slimbook-installer.desktop /usr/share/applications/
        fi

        dpkg-divert --package ${PACKAGE_NAME} --no-rename --add ${ORIGINAL_FILE}
        mv ${ORIGINAL_FILE} ${DIVERT_FILE} || true
    ;;

    abort-upgrade|abort-deconfigure|abort-remove)
    ;;

    *)
    echo "$0 called with unknown argument \`$1'" 1>&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0
