#!/bin/sh

set -e

PACKAGE_NAME="calamares-settings-slimbook"
ORIGINAL_FILE="/usr/share/applications/calamares.desktop"
DIVERT_FILE="/usr/share/applications/calamares.desktop.divert"

case "$1" in
    upgrade|deconfigure)
    ;;

    remove|purge)

        mv ${DIVERT_FILE} ${ORIGINAL_FILE} || true
        dpkg-divert --package  ${PACKAGE_NAME} --no-rename --remove ${ORIGINAL_FILE}|| true

    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
